apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-scripts
  namespace: atat
data:
  atat.sh:  |
    #!/bin/bash
    set -e
    mongo --username admin --password $MONGODB_ADMIN_PASSWORD --authenticationDatabase admin --host mongodb/mongodb-0.mongodb-svc.atat:27017,mongodb-1.mongodb-svc.atat:27017,mongodb-2.mongodb-svc.atat:27017 <<EOF
    use atat;
    db.createUser({
      user: 'atat',
      pwd: '$MONGODB_ATAT_PASSWORD',
      roles: [{
        role: 'readWrite',
        db: 'atat'
      }]
    });
    db.createCollection('delete_me');
    EOF
  rabbitmq.sh:  |
    #!/bin/bash
    set -e
    mongo --username admin --password $MONGODB_ADMIN_PASSWORD --authenticationDatabase admin --host mongodb/mongodb-0.mongodb-svc.atat:27017,mongodb-1.mongodb-svc.atat:27017,mongodb-2.mongodb-svc.atat:27017 <<EOF
    use rabbitmq;
    db.createUser({
      user: 'rabbitmq',
      pwd: '$MONGODB_RABBITMQ_PASSWORD',
      roles: [{
        role: 'readWrite',
        db: 'rabbitmq'
      }]
    });
    db.createCollection('delete_me');
    db.changeUserPassword('rabbitmq', '$MONGODB_RABBITMQ_PASSWORD');
    EOF