apiVersion: v1
kind: Service
metadata:
  name: atat-backend-service
  namespace: atat
spec:
  type: LoadBalancer
  selector:
    app: atat-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80