#!/bin/bash
FILE=./export.sh

echo "MONGO_INITDB_DATABASE: "
read MONGO_INITDB_DATABASE
echo "MONGO_INITDB_ROOT_USERNAME: "
read MONGO_INITDB_ROOT_USERNAME
echo "MONGO_INITDB_ROOT_PASSWORD: "
read MONGO_INITDB_ROOT_PASSWORD
echo "MONGO_ATAT_USERNAME: "
read MONGO_ATAT_USERNAME
echo "MONGO_ATAT_PASSWORD: "
read MONGO_ATAT_PASSWORD
echo "RABBITMQ_DEFAULT_USER: "
read RABBITMQ_DEFAULT_USER
echo "RABBITMQ_DEFAULT_PASS: "
read RABBITMQ_DEFAULT_PASS
echo "RABBITMQ_MONGO_DB: "
read RABBITMQ_MONGO_DB
echo "RABBITMQ_MONGO_USERNAME: "
read RABBITMQ_MONGO_USERNAME
echo "RABBITMQ_MONGO_PASSWORD: "
read RABBITMQ_MONGO_PASSWORD

echo "#!/bin/bash" >> $FILE
echo "export MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE" >> $FILE
echo "export MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >> $FILE
echo "export MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >> $FILE
echo "export MONGO_ATAT_USERNAME=$MONGO_ATAT_USERNAME" >> $FILE
echo "export MONGO_ATAT_PASSWORD=$MONGO_ATAT_PASSWORD" >> $FILE
echo "export ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME" >> $FILE
echo "export ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >> $FILE
echo "export RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER" >> $FILE
echo "export RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS" >> $FILE
echo "export RABBITMQ_MONGO_DB=$RABBITMQ_MONGO_DB" >> $FILE
echo "export RABBITMQ_MONGO_USERNAME=$RABBITMQ_MONGO_USERNAME" >> $FILE
echo "export RABBITMQ_MONGO_PASSWORD=$RABBITMQ_MONGO_PASSWORD" >> $FILE

chmod +x $FILE
sudo cp $FILE /etc/profile.d/
sudo cp $FILE ~/.bash_profile
rm $FILE