apiVersion: v1
kind: Secret
metadata:
  name: mongodb-db-credentials
type: Opaque
data:
  MONGODB_ATAT_USERNAME: {{ .Values.mongo_atat_usr | b64enc }}
  MONGODB_ATAT_PASSWORD: {{ .Values.mongo_atat_psw | b64enc }}
  MONGO_ATAT_DATABASE: {{ .Values.mongo_atat_db | b64enc }}
  MONGODB_RABBITMQ_USERNAME: {{ .Values.mongo_rmq_usr | b64enc }}
  MONGODB_RABBITMQ_PASSWORD: {{ .Values.mongo_rmq_psw | b64enc }}
  MONGO_RABBITMQ_DATABASE: {{ .Values.mongo_rmq_db | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
data:
  atat.sh: |
    #!/bin/bash
    mongo --username root --password $MONGODB_ROOT_PASSWORD <<EOF
    use $MONGO_ATAT_DATABASE;
    db.createUser({
      user: '$MONGODB_ATAT_USERNAME',
      pwd: '$MONGODB_ATAT_PASSWORD',
      roles: [{
        role: 'readWrite',
        db: '$MONGO_ATAT_DATABASE'
      }]
    });
    db.createCollection('delete_me');
    EOF
  rabbitmq.sh:  |
    #!/bin/bash
    mongo --username root --password $MONGODB_ROOT_PASSWORD <<EOF
    use $MONGO_RABBITMQ_DATABASE;
    db.createUser({
      user: '$MONGODB_RABBITMQ_USERNAME',
      pwd: '$MONGODB_RABBITMQ_PASSWORD',
      roles: [{
        role: 'readWrite',
        db: '$MONGO_RABBITMQ_DATABASE'
      }]
    });
    db.createCollection('delete_me');
    EOF