# We will use the latest Ubuntu image
FROM ubuntu:latest

# Add basic metadata
MAINTAINER Shan Tharanga "stwm2@student.london.ac.uk"

# We then copy the the wsgi and requirements
COPY requirements.txt wsgi.py /home/atat/

# Update the package manager
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.8 && \
    apt install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*
