version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_ATAT_USERNAME
      - MONGO_ATAT_PASSWORD
      - RABBITMQ_MONGO_DB
      - RABBITMQ_MONGO_USERNAME
      - RABBITMQ_MONGO_PASSWORD
    volumes:
      - type: bind
        source: './.docker/init-scripts'
        target: '/docker-entrypoint-initdb.d'
        read_only: true
      - type: bind
        source: './.docker/.mongodb'
        target: '/home/mongodb'
        read_only: false

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    ports:
    - 5672:5672
    - 15672:15672
