version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_ATAT_USERNAME
      - MONGO_ATAT_PASSWORD
    volumes:
      - type: bind
        source: './.docker/init-scripts/mongo-init.sh'
        target: '/docker-entrypoint-initdb.d/mongo-init.sh'
        read_only: true

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
