version: '3.2'

services:
    mongo:
        image: mongo
        container_name: "mongodb"
        environment:
          MONGO_DATA_DIR: /data/db
          MONGO_LOG_DIR: /dev/null
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:

          - './test:/test'
          - './lala/mongod.conf:/etc/mongod.conf'
        ports:
            - 27017:27017
        command:
          - '--auth'
          - '-f'
          - '/etc/mongod.conf'
    
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
      mongodb_data_volume: