apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: viva_atat
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.4-bionic"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
  env:
    - name: MANAGED_SECURITY_CONTEXT
      value: 'true'
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib