apiVersion: apps/v1
kind: Deployment
metadata:
  name: atat-workers-deployment
  namespace: atat
spec:
  selector:
    matchLabels:
      app: atat-workers
  replicas: 1
  template:
    metadata:
      labels:
        app: atat-workers
    spec:
      containers:
        - name: atat-workers-default
          image: registry.digitalocean.com/viva-perdana/atat-base:latest
          env:
            - name: MONGODB_ATAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-atat
                  key: password
            - name: MONGODB_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-rabbitmq
                  key: password
          envFrom:
            - secretRef:
                name: rabbitmq-atat-default-user
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - >-
              cd /home/atat/ &&
              pip3 install -r requirements.txt &&
              pip3 install celery &&
              celery -A atat.celery_app worker --loglevel=debug
        - name: atat-workers-atat
          image: registry.digitalocean.com/viva-perdana/atat-base:latest
          env:
            - name: MONGODB_ATAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-atat
                  key: password
            - name: MONGODB_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-rabbitmq
                  key: password
          envFrom:
            - secretRef:
                name: rabbitmq-atat-default-user
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c" ]
          args:
            - >-
              cd /home/atat/ &&
              pip3 install -r requirements.txt &&
              pip3 install celery &&
              celery -A atat.celery_app worker -Q ATAT -n ATAT --loglevel=debug
        - name: atat-workers-hunana
          image: registry.digitalocean.com/viva-perdana/atat-base:latest
          env:
            - name: MONGODB_ATAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-atat
                  key: password
            - name: MONGODB_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-rabbitmq
                  key: password
          envFrom:
            - secretRef:
                name: rabbitmq-atat-default-user
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c" ]
          args:
            - >-
              cd /home/atat/ &&
              pip3 install -r requirements.txt &&
              pip3 install celery &&
              celery -A atat.celery_app worker -Q Hunana -n Hunana --loglevel=debug
        - name: atat-workers-job
          image: registry.digitalocean.com/viva-perdana/atat-base:latest
          env:
            - name: MONGODB_ATAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-atat
                  key: password
            - name: MONGODB_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-rabbitmq
                  key: password
          envFrom:
            - secretRef:
                name: rabbitmq-atat-default-user
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c" ]
          args:
            - >-
              cd /home/atat/ &&
              pip3 install -r requirements.txt &&
              pip3 install celery &&
              celery -A atat.celery_app worker -Q Job -n Job --loglevel=debug
        - name: atat-workers-warehousing
          image: registry.digitalocean.com/viva-perdana/atat-base:latest
          env:
            - name: MONGODB_ATAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-atat
                  key: password
            - name: MONGODB_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-rabbitmq
                  key: password
          envFrom:
            - secretRef:
                name: rabbitmq-atat-default-user
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c" ]
          args:
            - >-
              cd /home/atat/ &&
              pip3 install -r requirements.txt &&
              pip3 install celery &&
              celery -A atat.celery_app worker -Q Warehousing -n Warehousing --loglevel=debug
