apiVersion: apps/v1
kind: Deployment
metadata:
  name: atat-backend-deployment
  namespace: atat
spec:
  selector:
    matchLabels:
      app: atat-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: atat-backend
    spec:
      containers:
        - name: atat-backend
          image: registry.digitalocean.com/viva-perdana/atat-base:latest
          env:
            - name: MONGODB_ATAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pwd-secret
                  key: MONGODB_ATAT_PASSWORD
            - name: MONGODB_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pwd-secret
                  key: MONGODB_RABBITMQ_PASSWORD
            - name: RABBITMQ_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-broker
                  key:  rabbitmq-password
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - >-
              cd /home/atat/ &&
              pip3 install -r requirements.txt &&
              gunicorn --bind 0.0.0.0:80 wsgi:app
