apiVersion: v1
kind: Service
metadata:
  name: atat-backend-service
spec:
  type: ClusterIP
  selector:
    app: atat-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80