from dashboard.eventhandlers.result_page_load import position_dropdown_update
from dashboard.eventhandlers.position_update_variants import position_update_variants_eventhandler
from dashboard.eventhandlers.position_update_statistics import position_update_statistics_eventhandler
from dashboard.eventhandlers.variant_update_eventhandler import variant_update_eventhandler
from dashboard.eventhandlers.reservoir_variant_update import reservoir_variant_update_eventhandler
from dashboard.eventhandlers.host_variant_update import host_variant_update_eventhandler
