name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v2
        with:
          path: './backend'
      - name: Checkout Frontend Repository
        uses: actions/checkout@v2
        with:
          path: './frontend'
          repository: 'ShanWeera/atat-single-frontend'
      - name: Update Package Manager
        run:  sudo apt update
      - name: Install DigitalOcean
        run: |
          echo 'Installing DigitalOcean'
          wget https://github.com/digitalocean/doctl/releases/download/v1.58.0/doctl-1.58.0-linux-amd64.tar.gz
          tar xf ./doctl-1.58.0-linux-amd64.tar.gz
          sudo mv ./doctl /usr/local/bin
      - name: Set-up DigitalOcean
        run:  doctl auth init -t ${{ secrets.DO_API_TOKEN }}
      - name: Install Docker
        run:  |
                sudo apt install apt-transport-https ca-certificates curl software-properties-common
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
                sudo apt update
                sudo apt-cache policy docker-ce
                sudo apt install docker-ce
      - name: Build ATAT Base Image
        run:  docker build -t atat-backend ./backend
      - name: Login to DigitalOcean Container Registry
        run:  doctl registry login
      - name: Push Image to Container Registry
        run:  |
                docker tag atat-backend registry.digitalocean.com/viva-perdana/atat-backend:latest
                docker push registry.digitalocean.com/viva-perdana/atat-backend:latest
      - name: Install Kubernetes
        run: |
          echo 'Installing dependencies.'
          sudo apt install -y apt-transport-https
          echo 'Downloading Google Cloud public signing key.'
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo 'Adding Kubernetes apt repository.' &&
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          echo 'Updating package index with new repository.'
          sudo apt update
          echo 'Installing Kubernetes.'
          sudo apt install -y kubectl
          kubectl version
      - name: Configure Kubernetes
        env:
          PERDANA_KUBERNETES: ${{secrets.PERDANA_KUBERNETES}}
        run:  |
          mkdir ~/.kube
          touch ~/.kube/config
          echo "$PERDANA_KUBERNETES" > ~/.kube/config
      - name: Install Helm
        run:  |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt update
          sudo apt install -y helm
      - name: Add Bitnami Repository to Helm
        run:  helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Set Preferred Namespace
        run:  kubectl config set-context --current --namespace=atat-dev
      - name: Create Namespace
        run:  kubectl create namespace atat-dev --dry-run=client -o yaml | kubectl apply --namespace=atat-dev -f -
      - name: Create DigitalOcean Container Registry Secret
        run:  |
          doctl registry kubernetes-manifest | sed "s/default/atat-dev/g" | kubectl apply -n atat-dev -f -
          doctl registry kubernetes-manifest | sed "s/default/atat-dev/g"
      - name: Create RabbitMQ Broker Password Secret
        run:  kubectl create secret generic rabbitmq-broker --from-literal='rabbitmq-password=${{ secrets.RABBITMQ_BROKER_PASSWORD }}' --from-literal='rabbitmq-erlang-cookie=${{ secrets.RABBITMQ_ERLANG_COOKIE }}' --save-config --dry-run=client -o yaml | kubectl apply -f -
      - name: Create MongoDB Password Secrets
        run:  helm upgrade mongodb-pwd-secret --install ./backend/.kubernetes/.mongodb/mongodb-secrets-helm --set atat=${{ secrets.MONGODB_ATAT_PASSWORD }} --set rabbitmq=${{ secrets.MONGODB_RABBITMQ_PASSWORD }} --set admin=${{ secrets.MONGODB_ADMIN_PASSWORD }}
      - name: Deploy RabbitMQ Replica Set
        run:  helm upgrade rabbitmq bitnami/rabbitmq --install -f ./backend/.kubernetes/.rabbitmq/deployment.yaml --set global.storageClass=freenas-nfs-csi
      - name: Deploy MongoDB Replica Set
        run:  helm upgrade mongodb bitnami/mongodb --install -f ./backend/.kubernetes/.mongodb/deployment.yaml --set auth.rootPassword=${{ secrets.MONGODB_ADMIN_PASSWORD }} --set auth.replicaSetKey=${{ secrets.MONGODB_REPLICA_SET_KEY }} --set global.storageClass=freenas-nfs-csi
      - name: Deploy ATAT Service
        run:  kubectl apply -f ./backend/.kubernetes/.atat/service.yaml
      - name: Deploy ATAT Replica Set
        run:  kubectl apply -f ./backend/.kubernetes/.atat/deployment.yaml
      - name: Deploy Celery Workers
        run:  kubectl apply -f ./backend/.kubernetes/.workers/deployment.yaml