name: Python package

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build:
    if: github.event.pull_request.merged == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run development setup
      run:  poetry run setup

    - name: Run Python Tests
      run:  poetry run coverage run -m pytest -v
